import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/Components/Navbar/Navbar'
import Input from '@/Components/Input/Input'
import Footer from '@/Components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gem Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="" >
        
        <div className=" h-96 w-full bg-cover bg-center ">
          <Image src="/Restaurant.jpg" alt="landing page" className="w-full h-full object-cover absolute mix-blend-overlay -z-10 blur-xs" width={1300} height={ 50} />
        </div>
        <Navbar />
        <Input />
        <div className="flex flex-row text-l pt-3 justify-center">
          <p className="pr-2 text-red-900 font-black text-xl cursor-pointer">Login</p>
        <p className="text-gray-100">for your recent addresses</p>
        </div>
        <Footer />  
      </main>
    </>
  )
}
